[module]
  [module.hugoVersion]
    min = "0.64.1"
    extended = false
  [[module.mounts]]
    source = "home"
    target = "content/home"
  [[module.mounts]]
    source = "authors"
    target = "content/authors"
  